version: '3.8'

services:

  # Web Server Service
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app
      - db

  #Database Service
  db:
    image : mysql
    container_name : mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

  # Application Service
  app:
    container_name: ${APP_CONTAINER}
    build: 
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www
    ports:
      - "9000:9000"
    working_dir: /var/www
  
  #Supervisor Service
  supervisor:
    build:
      context: ./docker/supervisor
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www
    command: 
      - /bin/sh
      - -c
      - supervisord -c /var/www/supervisord.conf 
      - supervisorctl  start all
    depends_on:
      - app
  
  #phpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "${PHP_MY_ADMIN_PORT}:80"
    depends_on:
      - db
